services:
  app:
    image: task-next
    build:
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma db push && npm run dev"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
